mkdir -p icons/Calico/actions
mkdir -p icons/Calico/events
mkdir -p icons/Calico/restree

mv raster/Icon_CheckMark.png              icons/Calico/actions/accept.png
mv raster/Icon_RedX.png                   icons/Calico/actions/cancel.png
mv raster/Icon_CascadeWindows.png         icons/Calico/actions/cascade.png
mv raster/Icon_Palette.png                icons/Calico/actions/colorize.png
mv raster/Icon_BuildBinary.png            icons/Calico/actions/compile.png
mv raster/Icon_Copy.png                   icons/Calico/actions/copy.png
mv raster/Icon_Cut.png                    icons/Calico/actions/cut.png
mv raster/Icon_Bug_Red_Spots.png          icons/Calico/actions/debug.png
mv raster/Icon_Problem.png                icons/Calico/actions/delete.png
mv raster/Icon_ArrowRun.png               icons/Calico/actions/execute.png
mv raster/Icon_Search.png                 icons/Calico/actions/find.png
mv raster/Icon_Help.png                   icons/Calico/actions/help.png
mv raster/Icon_Goto.png                   icons/Calico/actions/line-goto.png
mv raster/Icon_Book.png                   icons/Calico/actions/manual.png
mv raster/Icon_Highlighter.png            icons/Calico/actions/marker.png
mv raster/Icon_NewPlus.png                icons/Calico/actions/new.png
mv raster/Icon_SimpleArrowRight.png       icons/Calico/actions/next.png
mv raster/Icon_ActionFolder_Paper.png     icons/Calico/actions/open.png
mv raster/Icon_ActionFolder_Filmstrip.png icons/Calico/actions/open-strip.png
mv raster/Icon_ActionFolder_Photo.png     icons/Calico/actions/open-subimage.png
mv raster/Icon_Clipboard.png              icons/Calico/actions/paste.png
mv raster/Icon_SettingsWindow.png         icons/Calico/actions/preferences.png
mv raster/Icon_SimpleArrowLeft.png        icons/Calico/actions/previous.png
mv raster/Icon_Printer.png                icons/Calico/actions/print.png
mv raster/Icon_Broom.png                  icons/Calico/actions/rebuildall.png
mv raster/Icon_Redo.png                   icons/Calico/actions/redo.png
mv raster/Icon_SettingsBox.png            icons/Calico/actions/rename.png
mv raster/Icon_Save.png                   icons/Calico/actions/save.png
mv raster/Icon_SaveAll.png                icons/Calico/actions/save-all.png
mv raster/Icon_SaveAs.png                 icons/Calico/actions/save-as.png
mv raster/Icon_Settings.png               icons/Calico/actions/set.png
mv raster/Icon_Playback_Play.png          icons/Calico/actions/sound-play.png
mv raster/Icon_Playback_Stop.png          icons/Calico/actions/sound-stop.png
mv raster/Icon_Bold.png                   icons/Calico/actions/text-bold.png
mv raster/Icon_Italics.png                icons/Calico/actions/text-italic.png
mv raster/Icon_Underline.png              icons/Calico/actions/text-underlined.png
mv raster/Icon_Undo.png                   icons/Calico/actions/undo.png
mv raster/Icon_ZoomIn.png                 icons/Calico/actions/zoom-in.png
mv raster/Icon_ZoomOut.png                icons/Calico/actions/zoom-out.png

mv raster/Icon_AlarmClock.png                icons/Calico/events/alarm.png
mv raster/Icon_ActionFolder_AlarmClock.png   icons/Calico/events/alarmfolder.png
mv raster/Icon_Collision.png                 icons/Calico/events/collision.png
mv raster/Icon_ActionFolder_Collision.png    icons/Calico/events/collisionfolder.png
mv raster/Icon_LightBulb.png                 icons/Calico/events/create.png
mv raster/Icon_Bomb.png                      icons/Calico/events/destroy.png
mv raster/Icon_Paintbrush.png                icons/Calico/events/draw.png
mv raster/Icon_LightningBolt.png             icons/Calico/events/event.png
mv raster/Icon_Keyboard.png                  icons/Calico/events/keyboard.png
mv raster/Icon_ActionFolder_Keyboard.png     icons/Calico/events/keyboardfolder.png
mv raster/Icon_KeyDown.png                   icons/Calico/events/keypress.png
mv raster/Icon_ActionFolder_KeyDown.png      icons/Calico/events/keypressfolder.png
mv raster/Icon_KeyUp.png                     icons/Calico/events/keyrelease.png
mv raster/Icon_ActionFolder_KeyUp.png        icons/Calico/events/keyreleasefolder.png
mv raster/Icon_Mouse.png                     icons/Calico/events/mouse.png
mv raster/Icon_ActionFolder_Mouse.png        icons/Calico/events/mousefolder.png
mv raster/Icon_Wand.png                      icons/Calico/events/other.png
mv raster/Icon_ActionFolder_Wand.png         icons/Calico/events/otherfolder.png
mv raster/Icon_Step.png                      icons/Calico/events/step.png
mv raster/Icon_ActionFolder_Step.png         icons/Calico/events/stepfolder.png

mv raster/Icon_Photo.png               icons/Calico/restree/background.png
mv raster/Icon_Extension_CC.png        icons/Calico/restree/extension.png
mv raster/Icon_Font2.png               icons/Calico/restree/font.png
mv raster/Icon_Wrench.png              icons/Calico/restree/gm.png
mv raster/Icon_Folder2_Brown.png       icons/Calico/restree/group.png
mv raster/Icon_OpenFolder2_Brown.png   icons/Calico/restree/group-open.png
mv raster/Icon_InfoButton.png          icons/Calico/restree/info.png
mv raster/Icon_Object_GMB.png          icons/Calico/restree/object.png
mv raster/Icon_Path_CC.png             icons/Calico/restree/path.png
mv raster/Icon_Room_GMB.png            icons/Calico/restree/room.png
mv raster/Icon_Script_CC.png           icons/Calico/restree/script.png
mv raster/Icon_Speaker.png             icons/Calico/restree/sound.png
mv raster/Icon_Sprite_CC.png           icons/Calico/restree/sprite.png
mv raster/Icon_Timeline_CC.png         icons/Calico/restree/timeline.png
mv raster/Icon_ShaderScript_CC.png     icons/Calico/restree/shaderscript.png
